# Лабораторная работа №3. NumPy

## Задание

In [2]:
import numpy as np
np.version.version

'2.0.2'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [31]:
z = np.random.randint(0, 100, size=(10, 10))
print(z)
print(f"Минимум: {np.min(z)}, Максимум: {np.max(z)}")

[[ 3 36 39 18 34 82 43 94 71  6]
 [60 48 13 41  0 39 77 45 80 95]
 [33 94 75 27  5 84 75 15 53 12]
 [23 97 85 41 42 83 13  4 37 48]
 [14 25 91 66 54 20 90 50 26 56]
 [90 46 72 63 86 40 47 16 41  7]
 [10 82 58 25 10 41 86 70 10  2]
 [77 23 88 40 21 43 85 58 59 97]
 [ 8 21 85 10 36 59 22 27 82 29]
 [39 17  7 56 59  9 50 59 34 34]]
Минимум: 0, Максимум: 97


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [26]:
z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1  # нечетные строки, четные столбцы
z[::2, 1::2] = 1  # четные строки, нечетные столбцы
print(z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [39]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [43]:
z = np.random.rand(5, 10)
row_means = np.mean(z, axis=1, keepdims=True)

result = z - row_means

print("Исходная матрица:")
print(z)
print("\nСредние значения строк (исходные):")
print(np.mean(z, axis=1))
print("\nРезультат после вычитания среднего:")
print(result)

Исходная матрица:
[[0.83859756 0.67716838 0.71387532 0.0996603  0.91060708 0.27483619
  0.89828138 0.40462377 0.32499351 0.34161122]
 [0.89256711 0.00781553 0.31788114 0.19372163 0.3537713  0.8245047
  0.76433828 0.72978646 0.13229111 0.60260244]
 [0.51080861 0.57678471 0.46445984 0.80179266 0.57920282 0.81389116
  0.89097773 0.01619463 0.36453747 0.61307445]
 [0.68985836 0.24983607 0.88342614 0.90828521 0.78795184 0.47205571
  0.09443766 0.38672355 0.99586846 0.75439354]
 [0.11730738 0.66415115 0.05311386 0.56318608 0.99574869 0.492211
  0.47042932 0.88506339 0.10606338 0.84910434]]

Средние значения строк (исходные):
[0.54842547 0.48192797 0.56317241 0.62228365 0.51963786]

Результат после вычитания среднего:
[[ 0.29017209  0.12874291  0.16544985 -0.44876517  0.36218161 -0.27358928
   0.34985591 -0.1438017  -0.22343196 -0.20681425]
 [ 0.41063914 -0.47411244 -0.16404683 -0.28820634 -0.12815667  0.34257673
   0.28241031  0.24785849 -0.34963686  0.12067447]
 [-0.0523638   0.0136123  -0.

5. Поменяйте 1 и 2 строки матрицы

In [44]:
z = np.arange(25).reshape(5,5)
z[[0,1]] = z[[1,0]]
print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [45]:
z = np.random.random((10,2))
X,Y = z[:,0], z[:,1]
R = np.hypot(X, Y)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.66162809 0.7681041  0.46585823 1.18842603 1.30597471 1.1157158
 1.11696882 0.21692341 0.77967621 0.93717571]
[0.73023683 0.32394618 0.52996427 0.92556338 0.74502698 0.99927596
 1.10178616 1.47021998 0.45547654 0.07896648]


7. Заменить максимальный элемент массива на ноль

In [48]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.55045814 0.16906275 0.17461201 0.2756939  0.53698898 0.73955895
 0.8741302  0.60650379 0.         0.53540561]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [50]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print(f"Исходный массив: {z}")
print(f"Индексы для добавления: {i}")
np.add.at(z, i, 1)
print(f"После добавления 1: {z}")

Исходный массив: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Индексы для добавления: [2 5 4 2 9 8 7 5 8 3 3 6 3 6 7 2 8 5 3 7]
После добавления 1: [1. 1. 4. 5. 2. 4. 3. 4. 4. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [51]:
z = np.array([1,2,3,4,5])
result = np.zeros(len(z) + (len(z) - 1) * 3)
result[::4] = zprint(f"Исходный вектор: {z}")
print(f"Результат с тремя нулями: {result}")
print()

Исходный вектор: [1 2 3 4 5]
Результат с тремя нулями: [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]



10. Найти ближайшее к заданному значению число в заданном массиве

In [57]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
nearest_index = np.argmin(np.abs(z - v))
nearest_value = z[nearest_index]
print(f"Искомое значение: {v:.1f}")
print(f"Ближайшее значение: {nearest_value}")
print(f"Индекс ближайшего значения: {nearest_index}")

Искомое значение: 79.8
Ближайшее значение: 80
Индекс ближайшего значения: 80


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])  #int64
np.array([1., 4, 2, 5, 3]) #float64
np.array([1, 4, 2, 5, 3], dtype='float128') #float128
np.array([1., 4, 2, 5, 3], dtype='complex128') #complex128
np.array([1, 4, 2, 5, 3], dtype ='float64') #float64
np.array([1, 4, 2, 5, 3], dtype =int64) #int64
np.array([1, 4, 2, 5, 3], dtype='bool') #bool
np.array([1, 4, 2, 5, 3], dtype='str') #str
np.array([1, 4, 2, 5, '3']) #str
np.array([1, -4, 2, 0, 1j]) #complex128
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1' #"41"
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1] #-4
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1] #0
np.array([1, -4, 2, 0, True], dtype='int64')[-1] #1
np.array([1, -4, 2, 0, 1j], dtype='int64')[1] #ошибка
np.array([1, -4, 2, 0, 1j], dtype='str')[-1] #"1j"
np.array([1, 4, 2, 5, '3'])[-1] * 3 # "333"
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float) # Массив 3*5 из единиц типа float
np.full((3, 5), 3.14) # Массив 3*5, заполненный 3.14
np.linspace(0, 1, 5) # [0., 0.25, 0.5, 0.75, 1.]
np.diag((1,3,5)) # Диагональная матрица с элементами 1,3,5
np.smile((1,3,5)) # Ошибка
np.random.random((3, 3)) #Массив 3x3 случайных чисел [0,1)
np.eye(3) # Единичная матрица 3x3
np.empty(3) # Массив из 3 неинициализированных элементов
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]  #3
X[-1,-1] #7
X[0:1,-1] #4
X[0:2,-1] #4, 8
X[0:2,0:2] #[3,5],[7,6]
X[1,1:3] #6, 8
X[1,:] #7, 6, 8, 8
X[1,:] #7, 6, 8, 8
X[:,:] #Весь массив
X[:] #Весь массив
X[::2,::2] #[3,2],[1,7]
X[0:3:2,0:3:2] #[3,2], [1,7]
X[::-1,::-1] #[[7, 7, 6, 1],
      [8, 8, 6, 7],
      [4, 2, 5, 3]]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2]) # Разделение по строкам
np.split(grid, [2], axis=1) # Разделение по столбцам
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1] # Конкатенация
    np.array([1, 2, 3]) + np.array([3, 2, 1]) # Поэлементное сложение
```

**7**. Как в CodeLab измерить время выполнения кода?

%timeit выражение

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M) #64
np.sum(M, axis=1) #[14, 29, 21]
np.sum(M, axis=0) #[11, 17, 17, 19]
np.sum(M, axis=2) #Ошибка
np.sum(M, 1) #[14, 29, 21]
sum(M) #[11, 17, 17, 19]
sum(M,1) #Ошибка
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3 # [False, False, False, True]
X < 3 # [True, True, False, False]
X[X < 3] #[1, 2]
X[X > 3] #[4]
X[X != 3] #[1,2,4]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

Преимущества NumPy над обычными списками:

*   Скорость: NumPy использует оптимизированный C-код
*   Память: Более эффективное хранение данных
*   Векторизация: Операции над всем массивом без циклов
*   Математические функции: Богатый набор математических операций
*   Интеграция: Хорошая совместимость с другими научными библиотеками

Основные причины преимущества:

*   Гомогенность данных (все элементы одного типа)
*   Фиксированный размер массива
*   Векторизованные операции
*   Оптимизированная низкоуровневая реализация на C